<?php
if (!defined('ABSPATH')) { exit; }

function vm_en_nav($active='') {
 $items=['home'=>'Home','about'=>'About us','accommodation'=>'Accommodation','gallery'=>'Gallery','beaches'=>'Beaches','buljarica'=>'Buljarica','contact'=>'Contact'];
 $out='';
 foreach($items as $slug=>$label){$href=$slug==='home'?home_url('/en/'):home_url('/en/'.$slug.'/');$cls=$active===$slug?' class="active" aria-current="page"':'';$out.='<a href="'.esc_url($href).'"'.$cls.'>'.esc_html($label).'</a>';}
 return $out;
}
function vm_en_header($active='') {
 $logo='https://raw.githubusercontent.com/ViaMare/viamare/main/via_mare_upscaled_4x%20%281%29.jpg';
 return '<div class="utility"><div class="container"><span>Buljarica · Montenegro · <span class="category-stars" aria-label="4 stars">★★★★</span></span><div class="vm-language-switch"><a href="'.esc_url(home_url('/')).'">MNE/SRB</a><span aria-hidden="true"> / </span><a class="active" href="'.esc_url(home_url('/en/')).'">EN</a></div></div></div><header><div class="container header-inner"><a class="logo" href="'.esc_url(home_url('/en/')).'" aria-label="Via Mare — Home"><img src="'.esc_url($logo).'" alt="Apartments Via Mare"></a><button class="menu-toggle" aria-label="Open menu">☰</button><nav class="main-nav">'.vm_en_nav($active).'</nav><a class="header-book" href="'.esc_url(home_url('/en/booking/')).'">Book now</a></div></header>';
}
function vm_en_footer() {
 $logo='https://raw.githubusercontent.com/ViaMare/viamare/main/via_mare_upscaled_4x%20%281%29.jpg';
 return '<footer><div class="container footer-grid"><div><img src="'.esc_url($logo).'" alt="Apartments Via Mare"><p>Four-star apartments in peaceful Buljarica, just a few minutes from the sea.</p></div><div><h4>Navigation</h4><a href="'.esc_url(home_url('/en/about/')).'">About us</a><a href="'.esc_url(home_url('/en/accommodation/')).'">Accommodation</a><a href="'.esc_url(home_url('/en/gallery/')).'">Gallery</a><a href="'.esc_url(home_url('/en/beaches/')).'">Beaches</a><a href="'.esc_url(home_url('/en/buljarica/')).'">Buljarica</a></div><div><h4>Location</h4><p>Buljarica bb<br>85300 Petrovac na Moru<br>Montenegro</p></div></div><div class="container copyright">© 2026 Apartments Via Mare · <span class="category-stars" aria-label="4 stars">★★★★</span></div></footer>';
}
function vm_en_document($title,$active,$body,$bodyClass='') {
 $t=trailingslashit(get_template_directory_uri());$base=trailingslashit(home_url('/en/'));
 $css_ver=(string)@filemtime(get_template_directory().'/assets/css/site.css');$js_ver=(string)@filemtime(get_template_directory().'/assets/js/site-en.js');
 return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.esc_html($title).' · Apartments Via Mare</title><link rel="stylesheet" href="'.esc_url($t.'assets/css/site.css?v='.$css_ver).'"><script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"></script><script>window.VM_EN_BASE='.wp_json_encode($base).';</script></head><body class="'.esc_attr($bodyClass).'">'.vm_en_header($active).'<main>'.$body.'</main>'.vm_en_footer().'<script src="'.esc_url($t.'assets/js/site-en.js?v='.$js_ver).'"></script></body></html>';
}
function vm_en_unit_data(){return [
'standard-triple-studio'=>['Standard Triple Studio with Balcony','Standard Triple Studio','30 m²','3','Ground / 1st floor','Balcony'],
'triple-studio-with-balcony'=>['Triple Studio with Balcony','Triple Studio with Balcony','30 m²','3','Ground / 1st floor','Balcony'],
'triple-studio-with-sea-view'=>['Triple Studio with Sea View','Triple Studio with Sea View','30 m²','3','2nd floor','Sea view'],
'standard-one-bedroom-apartment'=>['Standard One-Bedroom Apartment with Balcony','Standard One Bedroom Apartment','40 m²','4','Ground / 1st floor','Balcony'],
'one-bedroom-apartment-with-balcony'=>['One-Bedroom Apartment with Balcony','One-Bedroom Apartment with Balcony','40 m²','4','Ground / 1st floor','Balcony'],
'one-bedroom-apartment-with-sea-view'=>['One-Bedroom Apartment with Sea View','One-Bedroom Apartment with Sea View','40 m²','4','2nd floor','Sea view'],
'apartment-with-sea-view-attic'=>['Sea View Apartment – Attic','Apartment with Sea View - (Attic)','35 m²','3','Attic','Sea view']];}
function vm_en_unit_page($slug){
 $all=vm_en_unit_data();if(!isset($all[$slug]))return null;$u=$all[$slug];
 $fac=['Air conditioning','Free Wi-Fi','Private bathroom','Shower','Hair dryer','Towels and bed linen','Flat-screen TV','Refrigerator','Cooktop','Kitchenware','Private parking',$u[5]];
 $lis='';foreach($fac as $x)$lis.='<li>✓ '.esc_html($x).'</li>';
 $b='<section class="unit-hero" data-en-unit-hero="'.esc_attr($slug).'"><div class="container"><span class="kicker light">APARTMENTS VIA MARE · <span class="category-stars" aria-label="4 stars">★★★★</span></span><h1>'.esc_html($u[0]).'</h1><p>'.esc_html($u[2].' · up to '.$u[3].' guests · '.$u[4]).'</p></div></section>
 <section class="section soft"><div class="container"><span class="kicker">PHOTOS</span><h2>View the apartment</h2><div class="unit-gallery" data-en-unit="'.esc_attr($slug).'"><div class="loading">Loading photos…</div></div><div class="gallery-availability"><a class="gold-btn" href="'.esc_url(home_url('/en/booking/?unit='.$slug)).'">Check availability</a></div></div></section>
 <section class="section"><div class="container unit-layout"><div><span class="kicker">ACCOMMODATION</span><h2>Your own space by the sea.</h2><p class="large">'.esc_html($u[2]).' of private space for up to '.esc_html($u[3]).' guests, with a private bathroom and kitchen / kitchenette.</p><div class="suite-meta"><span><b>Area:</b> '.esc_html($u[2]).'</span><span><b>Capacity:</b> '.esc_html($u[3]).'</span><span><b>Floor:</b> '.esc_html($u[4]).'</span></div><h2>Apartment facilities</h2><ul class="facility-grid">'.$lis.'</ul></div></div></section>';
 return vm_en_document($u[0],'accommodation',$b,'vm-en-unit');
}
function vm_en_page($slug){
 $unit=vm_en_unit_page($slug);if($unit!==null)return $unit;
 switch($slug){
 case '':case 'home':
 $b='<section class="hero"><div id="hero-media" class="hero-media"></div><div class="hero-shade"></div><div class="container hero-content"><span class="hero-stars"><span class="category-stars" aria-label="4 stars">★★★★</span></span><h1>A place of peace and rest.<br><i>Close to the sea.</i></h1><p>14 apartments in Buljarica · 260 m from the beach · up to 48 guests</p><div><a class="gold-btn" href="'.esc_url(home_url('/en/booking/')).'">Book your stay</a><a class="outline-btn" href="'.esc_url(home_url('/en/gallery/')).'">View gallery</a></div></div></section>
 <section class="booking" id="booking"><form id="booking-form" class="container booking-grid"><label><span>Arrival</span><input name="arrival" type="date" required></label><label><span>Departure</span><input name="departure" type="date" required></label><label><span>Adults</span><select name="adults"><option>1</option><option selected>2</option><option>3</option><option>4</option></select></label><label><span>Children</span><select name="children"><option selected>0</option><option>1</option><option>2</option><option>3</option></select></label><label><span>Promo code</span><input name="promo" placeholder="Optional"></label><button class="gold-btn">Check</button></form><div class="container booking-result" id="booking-result"></div></section>
 <section class="story section"><div class="container story-grid"><div><span class="kicker">WELCOME TO VIA MARE</span><h2>A place where your holiday truly begins.</h2></div><div><p class="large">Apartments Via Mare is located in the peaceful coastal village of Buljarica, a few minutes’ walk from the beach and 2 km from Petrovac.</p><p>Fourteen accommodation units, with a total capacity of up to 48 guests, are set in a four-storey property. Studios are 30 m², one-bedroom apartments 40 m² and attic apartments 35 m². Guests have free private parking, Wi-Fi and a barbecue area, while transfers, excursions and car rental can be arranged on request.</p><a class="text-link" href="'.esc_url(home_url('/en/about/')).'">More about us →</a></div></div></section>
 <section class="highlights"><div class="container stats"><div><strong>14</strong><span>apartments</span></div><div><strong>7</strong><span>accommodation types</span></div><div><strong>260 m</strong><span>from the beach</span></div><div><strong>48</strong><span>guests</span></div><div><strong><span class="category-stars" aria-label="4 stars">★★★★</span></strong><span>category</span></div></div></section>
 <section class="section suites"><div class="container"><div class="section-head"><div><span class="kicker">ACCOMMODATION</span><h2>Find your apartment.</h2></div><a class="text-link" href="'.esc_url(home_url('/en/accommodation/')).'">View all 7 types →</a></div><div id="unit-grid" class="suite-grid"><div class="loading">Loading accommodation…</div></div></div></section>
 <section class="section amenities"><div class="container"><span class="kicker light">COMFORT WITHOUT COMPROMISE</span><h2>Everything you need for a carefree stay.</h2><div class="amenity-grid"><div>◌<b>Free Wi-Fi</b></div><div>⌂<b>Private parking</b></div><div>❄<b>Air conditioning</b></div><div>♨<b>Equipped kitchen</b></div><div>▱<b>Balcony / terrace</b></div><div>✈<b>Transfer on request</b></div><div>♨<b>Barbecue area</b></div><div>▣<b>Flat-screen TV</b></div></div></div></section>
 <section class="section history-teaser"><div class="container editorial-grid"><div><span class="kicker">MORE THAN A BEACH</span><h2>Buljarica, between the sea and history.</h2></div><div><p class="large">The long coastline, Buljarica field and Gradište Monastery create a place where nature and history meet just minutes from Via Mare.</p><a class="gold-btn" href="'.esc_url(home_url('/en/buljarica/')).'">The story of Buljarica</a></div></div></section>
 <section class="section payment-cta"><div class="container payment-cta-grid"><div><span class="kicker light">DIRECT AND SECURE</span><h2>Book and pay online.</h2><p>From choosing dates and an apartment to booking confirmation and payment — without leaving the Via Mare website.</p><a class="gold-btn" href="'.esc_url(home_url('/en/booking/')).'">Online booking and payment</a></div><div class="payment-panel"><b>3-D Secure</b><p>Designed for Visa and Mastercard cards.</p><hr><b>Clear price breakdown</b><p>Before confirmation, guests see the price, deposit and total amount.</p></div></div></section>';
 return vm_en_document('Home','home',$b,'vm-en-home');
 case 'about':
 $b='<section class="page-hero"><div class="container"><span class="kicker light">APARTMENTS VIA MARE</span><h1>About us</h1><p>Four stars, 14 apartments and a stay designed for guests who value their own space.</p></div></section>
 <section class="section"><div class="container editorial-grid"><div><span class="kicker">WELCOME</span><h2>Via Mare — apartment holidays in Buljarica.</h2></div><div><p class="large">Apartments Via Mare is located in Buljarica, a few minutes’ walk from the beach and around 2 km from Petrovac. The four-star property has 14 accommodation units arranged in seven accommodation types.</p><p class="large">Via Mare is intended for guests who want more space and independence during their holiday. Every apartment has a balcony, private bathroom, air conditioning and facilities for preparing food, with free Wi-Fi and private parking for guests.</p><p class="large">Studios are 30 m², one-bedroom apartments 40 m² and attic apartments 35 m². Depending on type, accommodation is for up to three or four guests, with total property capacity of up to 48 guests.</p></div></div></section>
 <section class="section soft"><div class="container"><span class="kicker">ACCOMMODATION</span><h2>14 apartments · 7 accommodation types</h2><div class="benefit-grid"><article><b>STUDIOS</b><h3>30 m²</h3><p>Triple studios with balconies, including units with sea views.</p></article><article><b>ONE-BEDROOM APARTMENTS</b><h3>40 m²</h3><p>More spacious accommodation for up to four guests, with a balcony and private kitchen.</p></article><article><b>ATTIC</b><h3>35 m²</h3><p>Apartments for up to three guests, with a balcony and sea view.</p></article><article><b>CATEGORY</b><h3><span class="category-stars" aria-label="4 stars">★★★★</span></h3><p>Via Mare is officially categorized with four stars.</p></article></div></div></section>
 <section class="section"><div class="container editorial-grid"><div><span class="kicker">COMFORT</span><h2>Everything needed for an independent and pleasant stay.</h2></div><div><p class="large">The apartments are arranged so guests have their own space for sleeping, relaxing and preparing meals, without giving up the conveniences that matter during a summer stay.</p><p>Facilities include an equipped kitchen, refrigerator, cooktop, kitchenware, flat-screen TV, air conditioning, private bathroom with shower and hair dryer, as well as towels and bed linen.</p><p>Private parking and a barbecue area are available at the property, while transfers can be arranged on request.</p></div></div></section>
 <section class="section soft"><div class="container editorial-grid"><div><span class="kicker">BULJARICA</span><h2>A quieter place to stay, close to Petrovac.</h2></div><div><p class="large">Via Mare’s location lets you spend the day on Buljarica Beach while keeping Petrovac, Lučice and other places on the Budva Riviera within easy reach.</p><p>Buljarica is also a convenient base for discovering Paštrovići and Gradište Monastery, so a stay here need not be limited to the beach and sea.</p><p><a class="text-link" href="'.esc_url(home_url('/en/buljarica/')).'">Learn more about Buljarica →</a></p></div></div></section>
 <section class="section"><div class="container editorial-grid"><div><span class="kicker">CHOOSE YOUR APARTMENT</span><h2>From studios to one-bedroom apartments with sea views.</h2></div><div><p class="large">Explore all seven accommodation types, their sizes, capacity, facilities and photographs, and choose the unit that best suits your stay.</p><p><a class="gold-btn" href="'.esc_url(home_url('/en/accommodation/')).'">View accommodation</a> <a class="text-link" href="'.esc_url(home_url('/en/gallery/')).'">Gallery →</a></p></div></div></section>';
 return vm_en_document('About us','about',$b);
 case 'accommodation':
 $b='<section class="page-hero"><div class="container"><span class="kicker light">7 ACCOMMODATION TYPES</span><h1>Apartments</h1><p>From triple studios to one-bedroom apartments for four guests.</p></div></section><section class="section"><div class="container"><div id="unit-grid" class="suite-grid"><div class="loading">Loading apartments…</div></div></div></section>';
 return vm_en_document('Accommodation','accommodation',$b);
 case 'gallery':
 $b='<section class="page-hero"><div class="container"><span class="kicker light">VIA MARE IN PICTURES</span><h1>Gallery</h1></div></section><section class="section gallery-section gallery-editorial"><div class="gallery-wide"><div class="gallery-heading"><div><span class="kicker">APARTMENTS VIA MARE</span><h2>Photo gallery</h2></div><button id="gallery-show-all" class="gallery-show-all" type="button">Show all 118 photos</button></div><div id="gallery-filters" class="gallery-filters" aria-label="Gallery filter"></div><div id="gallery-featured" class="gallery-featured"></div><div id="full-gallery" class="full-gallery" hidden></div></div></section>';
 return vm_en_document('Gallery','gallery',$b,'vm-page-gallery gallery-page');
 case 'beaches':
 $b='<section class="page-hero"><div class="container"><span class="kicker light">THE ADRIATIC WITHIN EASY REACH</span><h1>Beaches and coves</h1></div></section><section class="section soft"><div class="container beach-list"><article><div class="beach-num">01</div><div><h2>Buljarica</h2><p>About 260 m from Via Mare. A long, spacious coastline suitable for families and long days by the sea.</p></div></article><article><div class="beach-num">02</div><div><h2>Lučice</h2><p>A smaller green-framed cove between Buljarica and Petrovac.</p></div></article><article><div class="beach-num">03</div><div><h2>Petrovac</h2><p>The town beach beside the promenade, restaurants and evening life.</p></div></article><article><div class="beach-num">04</div><div><h2>Perazića Do and Drobni Pijesak</h2><p>Coves for guests who want to explore more of the Budva Riviera.</p></div></article></div></section>';
 return vm_en_document('Beaches','beaches',$b);
 case 'buljarica':
 $b='<section class="page-hero"><div class="container"><span class="kicker light">SEA · NATURE · CENTURIES OF HISTORY</span><h1>Buljarica</h1><p>A place where the Adriatic coast, Paštrovići and old monasteries meet in the same landscape.</p></div></section>
 <section class="section"><div class="container editorial-grid"><div><span class="kicker">THE PLACE</span><h2>The quieter side of the Budva Riviera.</h2></div><div><p class="large">South of Petrovac, Buljarica opens towards the sea with a broad coastline and spacious hinterland. Sea, field and hills remain part of one landscape.</p><p class="large">For Via Mare guests, this means being close to the beach while having an excellent base for Petrovac, Lučice and discovering the cultural landscape of Paštrovići.</p></div></div></section>
 <section class="section soft"><div class="container"><span class="kicker">PAŠTROVIĆI</span><h2>A region with a story much deeper than a summer resort.</h2><div class="experience-grid"><article><h3>Coastal history</h3><p>Buljarica belongs to the Paštrovići area, a historic community whose traces can be seen in old villages, churches and monasteries along the coast and inland.</p></article><article><h3>Gradište</h3><p>Gradište Monastery stands on a rise beside the Petrovac–Bar road. Tradition dates its foundation to 1116, while written documents first mention it in 1305.</p></article><article><h3>Three churches</h3><p>The complex includes the churches of St Nicholas, St Sava and the Dormition of the Mother of God, together with monastic quarters and walled monastery grounds.</p></article><article><h3>The 1597 primer</h3><p>Gradište is associated with an early primer printed in Venice in 1597 by the monks Stefan of Paštrovići and Sava.</p></article></div></div></section>
 <section class="history-band"><div class="container editorial-grid"><div><span class="kicker light">GRADIŠTE MONASTERY</span><h2>Centuries above Buljarica.</h2></div><div><p class="large">Gradište is more than a landmark; it is one of the important historical layers of this area.</p><p class="large">The monastery was long a dependency of Dečani. The main Church of St Nicholas preserves valuable wall paintings and an iconostasis. The complex was repeatedly destroyed, burned and rebuilt through history, and was restored again after the 1979 earthquake.</p><p class="large">The name Gradište is linked to “gradina”, referring to traces of an old settlement or fortification; ancient remains have also been found within the monastery grounds.</p></div></div></section>
 <section class="section"><div class="container"><span class="kicker">A DAY IN BULJARICA</span><h2>From a morning by the sea to an evening in Petrovac.</h2><div class="benefit-grid"><article><b>MORNING</b><h3>Buljarica Beach</h3><p>Start the day by the sea while the coast is still quiet.</p></article><article><b>NOON</b><h3>Gradište</h3><p>Visit the monastery complex and discover the cultural history of the area.</p></article><article><b>AFTERNOON</b><h3>Lučice and Petrovac</h3><p>Change the scenery with a short trip to nearby beaches and the town.</p></article><article><b>EVENING</b><h3>Coastal walk</h3><p>Return to the peace of Buljarica or spend the evening on the Petrovac promenade.</p></article></div></div></section>';
 return vm_en_document('Buljarica','buljarica',$b,'vm-page-buljarica');
 case 'contact':
 $b='<section class="page-hero contact-hero"><div class="container"><span class="kicker light">CONTACT</span><h1>We are here for all questions<br>about your stay.</h1></div></section>
 <section class="section contact-overview"><div class="container contact-overview-grid"><div class="contact-intro"><span class="kicker">APARTMENTS VIA MARE</span><h2>Contact and location</h2><p class="large">Via Mare is located in Buljarica, close to the sea and around 2 km from Petrovac.</p><p>For questions about apartments, dates or special requests, send us a message. To check accommodation, you can open the booking page directly.</p><a class="text-link" href="'.esc_url(home_url('/en/booking/')).'">Check accommodation →</a></div><div class="contact-facts"><div class="contact-fact"><span>ADDRESS</span><strong>Buljarica bb</strong><p>85300 Petrovac na Moru<br>Montenegro</p></div><div class="contact-fact"><span>ACCOMMODATION</span><strong>14 apartments</strong><p>7 accommodation types<br>up to 48 guests</p></div><div class="contact-fact"><span>SERVICES</span><strong>Private parking</strong><p>Free Wi-Fi<br>transfer on request</p></div></div></div></section>
 <section class="section soft contact-message-section"><div class="container contact-message-grid"><div><span class="kicker">SEND AN ENQUIRY</span><h2>How can we help?</h2><p>Enter your basic details and message. If you already know your travel dates, add the dates and number of guests.</p></div><form id="inquiry-form" class="inquiry refined-inquiry"><div class="two"><label><span>Full name *</span><input name="name" autocomplete="name" required></label><label><span>Email *</span><input name="email" type="email" autocomplete="email" required></label></div><div class="two"><label><span>Phone</span><input name="phone" type="tel" autocomplete="tel"></label><label><span>Number of guests</span><input name="guests" type="number" min="1" max="48"></label></div><div class="two"><label><span>Arrival</span><input name="checkin" type="date"></label><label><span>Departure</span><input name="checkout" type="date"></label></div><label><span>Message *</span><textarea name="message" rows="6" placeholder="Tell us what you would like to know..." required></textarea></label><div class="contact-submit-row"><button class="gold-btn" type="submit">Send enquiry</button><p id="form-status" class="form-status" aria-live="polite"></p></div></form></div></section>
 <section class="contact-map-block"><div class="container contact-map-title"><div><span class="kicker">FIND US</span><h2>Buljarica · Montenegro</h2></div><a class="text-link" href="https://www.google.com/maps/search/?api=1&query=Apartments+Via+Mare+Buljarica+Montenegro" target="_blank" rel="noopener">Open in Google Maps →</a></div><iframe class="contact-map-large" title="Apartments Via Mare — Buljarica" src="https://www.google.com/maps?q=Apartments%20Via%20Mare%20Buljarica%20Montenegro&output=embed" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></section>';
 return vm_en_document('Contact','contact',$b,'vm-page-kontakt');
 case 'booking':
 $b='<section class="page-hero"><div class="container"><span class="kicker light">DIRECT BOOKING</span><h1>Secure online payment</h1><p>The checkout is prepared for payment gateway and channel manager integration.</p></div></section><section class="section"><div class="container checkout-grid"><form id="checkout-form" class="checkout-card"><h2>Stay details</h2><div class="stay-dates"><label><span>Arrival</span><input name="arrival" type="date" required></label><label><span>Departure</span><input name="departure" type="date" required></label></div><label class="unit-select-label"><span>Accommodation type</span><select name="unit" id="payment-unit"><option value="">Select accommodation type</option></select></label><input name="name" required placeholder="Full name"><input name="email" type="email" required placeholder="Email"><h2>Payment method</h2><p>Visa / Mastercard / 3-D Secure will be enabled through a certified payment processor. Via Mare will not store card details.</p><button class="gold-btn">Continue to payment</button><p id="payment-status"></p></form><aside class="order-card"><div id="payment-unit-preview" class="payment-unit-preview"><div class="payment-unit-photo"></div><div><span class="kicker light">SELECTED ACCOMMODATION</span><h2 id="payment-unit-title">Select accommodation type</h2></div></div><div class="booking-summary"><h3>Your booking</h3><div class="summary-row"><span>Dates</span><strong id="summary-dates">—</strong></div><div class="summary-row"><span>Price</span><strong id="summary-price">—</strong></div><div class="summary-row"><span>Deposit</span><strong id="summary-deposit">—</strong></div><div class="summary-row"><span>Taxes</span><strong id="summary-taxes">—</strong></div><div class="summary-row summary-total"><span>Total</span><strong id="summary-total">—</strong></div><p class="summary-note">Amounts will be displayed once the price list and availability are connected.</p></div></aside></div></section>';
 return vm_en_document('Online booking','',$b);
 }
 return null;
}
